# Generated by Django 2.2.11 on 2020-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='no_of_facebook_likes',
            new_name='fb_likes',
        ),
    ]
