# Generated by Django 2.2.11 on 2020-03-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20200319_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='fb_likes',
        ),
    ]
